name: venv
channels:
  - conda-forge
  - pip
  - defaults
dependencies:
  - python=3.9.5
  - openai
  - graphdatascience
  - retry==0.9.2
  - langchain>=0.0.216
  - streamlit==1.23.1
  - streamlit-chat==0.0.2.2
  - numpy
  - pandas
  - plotly==5.15.0
  - altair<5
  - python-dotenv==1.0.0
  - langchain-community
  - langchain-openai
  - chromadb
  - ollama
  - imutils
  - Flask
  - Pillow
  - boto
  - pip
  - pip:
      - gunicorn
      - uvicorn
      - neo4j
      - opencv-python
      - opencv-python-headless
      - pypdfium2
      - streamlit-chat-media==0.0.4
      - json_repair==0.25.3
      - boto3
      - Flask[async]
      - faiss-cpu
      - python-unsplash
      - fastapi
